version: '3'


services:
  php:
    build:
      context: ../../
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - ADMIN_NAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password
    ports:
      - "5000:80"
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_gui:
    image: "adminer:4"
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  postgres_data:
  locker_db_data:
