version: '3'


services:
  php:
    build:
      context: ../../
    environment:
      - NODE_ENV=production
      - APP_NAME=LTI Shim
      - APP_ENV=local
      - APP_KEY=base64:m5LqBR7zPOhn0DJgiojINHaY/bXGJ+QUCxu2FHh2aWI=
      - APP_DEBUG=false
      - APP_URL=http://localhost:5000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SESSION_DRIVER=cookie
      - SANCTUM_STATEFUL_DOMAINS=localhost:5000
      - ADMIN_NAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password
    ports:
      - "5000:80"
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_gui:
    image: "adminer:4"
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  postgres_data:
  locker_db_data:
